import type { Metadata } from "next"

import { pretendard, hahmlet, source } from "@/fonts/font"

import { ThemeProvider } from "@/components/provider/theme/theme-provider"
import { Header } from "@/components/header/header"

import "@/styles/globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const RootLayout = ({
  children
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${pretendard.variable} ${hahmlet.variable} ${source.variable} bg-background min-h-screen`}>
        <ThemeProvider defaultTheme="dark" defaultThemeColor="purple">
          <div className="relative flex min-h-screen flex-col bg-background">
            <Header />
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}

export default RootLayout
